version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: svk_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"

    nginx:
        image: nginx:stable
        container_name: svk_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
